name: Test and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
      
      - name: Build the app
        run: npm run build
      
      - name: Start the server
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: NODE_ENV=production npm start > server.log 2>&1 &
      
      - name: Server status check
        run: |
          sleep 5
          ps aux | grep node
          cat server.log
          
      - name: Wait for server to be ready
        run: npx wait-on --timeout 60000 http://localhost:3001 || (cat server.log && exit 1)
      
      - name: Run Cypress tests
        run: npx cypress run --component

  deploy-to-render-staging:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render Staging
        run: curl ${{ secrets.RENDER_STAGING_DEPLOYHOOK }}

  deploy-to-render-production:
    runs-on: ubuntu-latest
    needs: deploy-to-render-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render Production
        run: curl ${{ secrets.RENDER_PRODUCTION_DEPLOYHOOK }}